name: Send Google Chat Checkout Reminder

on:
  schedule:
    - cron: '30 17 * * 1-5'
      timezone: 'Asia/Jakarta'

  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Reminder Script
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.CHAT_WEBHOOK_URL }}
        run: node send_reminder.js
